### ISSUE TITLE
Add .gitignore to prevent system-generated files from being tracked

### ISSUE THREAD

**Issue by lokranjanp** [nisbweb/Code-Alchemy#28]
I noticed that some system-generated files (.DS_Store, .vscode, etc.) are being tracked in the repository. These files are not relevant to the codebase and can create unnecessary clutter.

To resolve this, I propose adding a .gitignore file to exclude these files from being tracked, making the repository cleaner and easier to work with for all contributors.

**Comment by lokranjanp** [comment]
I have added a PR with the title : Feature/add gitignore : PR to untrack system generated files #29
Please review and merge.

**Comment by ashrith-vasist** [comment]
@lokranjanp I have merged the branch .
If no other issues , can we close this one ?

**Comment by lokranjanp** [comment]
No Issues. I will close the Issue, @ashrith-vasist .!
