### ISSUE TITLE
want to add a BFS and DFS traversal program

### ISSUE THREAD

**Issue by ScepticallySam** [nisbweb/Code-Alchemy#5]
I want to create a c++ program with my own binary tree class and show BFS and DFS traversals for hacktober2024

**Comment by MihirSaiDudekula** [comment]
I'd like to work on this too, and provide a solution in java for BFS and DFS graph traversals

**Comment by Haripriya-1212** [comment]
Sure, you can add your code file in the DSA practice folder and create a pull request.
