### ISSUE TITLE
Stack Implementation using Array

### ISSUE THREAD

**Issue by shubhamjain1402** [nisbweb/Code-Alchemy#53]
Hey @nisbweb,

I want to add a Stack Implementation using Array in the DSA practice folder under hacktoberfest 2024. [PR #54].

PS :- I also added the code for Insertion Sort Algorithm in C++.

**Comment by Haripriya-1212** [comment]
Hi!
There was a unimplemented part in stack code. I have commented it. You can correct and make a PR.
