### ISSUE TITLE
Add Maze Solver Implementation in C++

### ISSUE THREAD

**Issue by s-a-n-19** [nisbweb/Code-Alchemy#63]
I would like to propose the addition of a new feature: a Maze Solver implemented in C++. This program will take a 2D grid maze as input and find a path from the starting point to the goal, if one exists. The implementation will utilize Depth-First Search (DFS) and Backtracking techniques to explore potential paths within the maze.
Concepts: DFS, BFS, Backtracking
This addition will provide users with a practical example of solving mazes programmatically and enhance the project’s educational value.

Thus, I would like to work upon this issue, so can you please assign me this issue along with hacktoberfest-accepted label?

**Comment by Haripriya-1212** [comment]
Hi!
Yeah Sure! Good one .You can work on this. Add your code file/ folder in Projects Track and make a pull request. Will review and merge.
