### ISSUE TITLE
Want to add solution for Insertion Sort.cpp

### ISSUE THREAD

**Issue by redxz5** [nisbweb/Code-Alchemy#9]
Implementation in C++ language.

**Comment by aakashsharma7** [comment]
@redxz5 kindly assign this issue to me

**Comment by Haripriya-1212** [comment]
The code in your pr is selection sort and not insertion sort. So if you make another pr with right code we will merge it.

**Comment by aakashsharma7** [comment]
@Haripriya-1212 yeahh i will

**Comment by Haripriya-1212** [comment]
okk
